name: French Accent
favicon: null
layout_spectrum: 0.7900023846887052
typography_spectrum: 0.8287067268975079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#96a296'
    - '#697766'
    - '#1c291f'
    - '#d5e0e2'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
